name: R-CMD-check

on: [push, pull_request]

jobs:
  check:
    name: R-CMD-check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.2'

    - name: Install dependencies
      run: |
        install.packages(c('devtools', 'roxygen2'), repos = 'https://cloud.r-project.org/')
        devtools::install_deps()

    - name: Check package
      run: |
        devtools::check()
